config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :create_projects
  root 'pages#index'
  get '/about', to: 'pages#about'
  resources :projects
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'carrierwave'
  require 'carrierwave/orm/activerecord'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :projects
  has_many :portfolios
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :category
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @category = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      flash[:danger] = @category.errors.full_messages.to_sentence
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @project = Project.all
  end

  def about
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def index
    portfolio = Portfolio.all
  end

  def show
    portfolio = Portfolio.find(params[:id])
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    if @portfolio.save
      redirect_to @portfolio
    else
      flash[:danger] = @portfolio.errors.full_messages.to_sentence
      render 'new'
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:name, :description, :image, :category, :category_id, :link)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @category = Category.where name: params[:name]
  end

  # GET /projects/new
  def new
    @project = Project.new
    @category = Category.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project, {})
    end

    def project_params
      params.require(:project).permit(:name, :description, :image, :category_id, :link_string, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_projects_helper.rb
module CreateProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/categories/index.html.erb
<% @category.each do |category| %>
  <%= category.name %><br>
<% end %>

app/views/categories/new.html.erb
<div class="container page-content">
  <div class="row">
    <div class-"span12">
      <div class="box-container">
        <div style="margin-left: auto; margin-right: auto; width: 20em" ><br />
          <h2 class="page-title">Add category</h2>

          <%= simple_form_for(:category, html: { class: 'form-horizontal' }) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.submit "Opret", class: "btn span3 btn-realto-form btn-large" %>
          <% end %>
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_contact.html.erb
<!--CONTACT-->
<section id="contact" class="white-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h3 class="title-small">
          <span>Contact</span>
        </h3>
        <p class="content-detail">
          I'll reply you within 24 hours. If you can't wait, then don't hesitate to contact me on <a href="https://www.facebook.com/preisler.io/" style="color:#527bbb" target="_blank">Facebook</a> or <a href="https://www.instagram.com/jonaspreisler/" style="color:#8a3ab9" target="_blank" data-hover="Instagram">Instagram</a>. Or send me a text message at +4542836608.
        </p>

      </div>
      <div class="col-md-9 content-right">
        <form>
          <div class="group">
            <input required="" type="text"><span class="highlight"></span><span class="bar"></span><label>Name</label>
          </div>
          <div class="group">
            <input required="" type="email"><span class="highlight"></span><span class="bar"></span><label>Email</label>
          </div>
          <div class="group">
            <textarea required=""></textarea><span class="highlight"></span><span class="bar"></span><label>Message</label>
          </div>
          <input id="sendMessage" name="sendMessage" type="submit" value="Send Message">
        </form>
      </div>
    </div>
  </div>
</section>
<!--/.CONTACT END-->

app/views/layouts/_footer.html.erb
<footer>
    <div class="container-fluid">
        <p class="copyright">hello@jonaspreisler.com <br> © Preisler 2017</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Box personal portfolio Template</title>
    <link rel="icon" href="img/fav.png" type="image/x-icon">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="ionicons/css/ionicons.min.css" rel="stylesheet">

    <!-- main css -->
    <link href="css/style.css" rel="stylesheet">


    <!-- modernizr -->
    <script src="js/modernizr.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<div class="box-header">
    <div class="box-logo">
        <%= link_to 'PREISLER', root_path, class: "logo2" %>
    </div>
    <!-- box-nav -->
    
    <!-- box-primary-nav-trigger -->
</div>

app/views/layouts/_header2.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Box personal portfolio Template</title>
    <link rel="icon" href="img/fav.png" type="image/x-icon">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="ionicons/css/ionicons.min.css" rel="stylesheet">

    <!-- main css -->
    <link href="css/style.css" rel="stylesheet">


    <!-- modernizr -->
    <script src="js/modernizr.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<div class="box-header">
    <div class="box-logo">
        <p class="logo">PREISLER</p>
        <br>
        <%=  link_to 'Go back', root_path %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Preisler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="js/jquery-2.1.1.js"></script>
    <!--  plugins -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/menu.js"></script>
    <script src="js/animated-headline.js"></script>
    <script src="js/isotope.pkgd.min.js"></script>


    <!--  custom script -->
    <script src="js/custom.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
hello!

app/views/pages/index.html.erb
<body>

    <!-- Preloader -->
    <div id="preloader">
        <div class="pre-container">
            <div class="spinner">
                <div class="double-bounce1"></div>
                <div class="double-bounce2"></div>
            </div>
        </div>
    </div>
    <!-- end Preloader -->

    <div class="">

        <!-- nav -->
        <nav>
            <ul class="box-primary-nav">
                <li class="box-label">About me</li>

                <li><a href="index.html">Intro</a> <i class="ion-ios-circle-filled color"></i></li>
                <li><%= link_to 'About me', about_path %></li>
                <li><a href="services.html">services</a></li>
                <li><a href="portfolio.html">portfolio</a></li>
                <li><a href="contact.html">contact me</a></li>



                <li class="box-label">Follow me</li>

                <li class="box-social"><a href="#0"><i class="ion-social-facebook"></i></a></li>
                <li class="box-social"><a href="#0"><i class="ion-social-instagram-outline"></i></a></li>
                <li class="box-social"><a href="#0"><i class="ion-social-twitter"></i></a></li>
                <li class="box-social"><a href="#0"><i class="ion-social-dribbble"></i></a></li>
            </ul>
        </nav>
        <!-- end nav -->
        <%= render 'layouts/header' %>
        <!-- box-intro -->
        <section class="box-intro">
            <div class="table-cell">
                <h1 class="box-headline letters rotate-2">
                    <span class="box-words-wrapper">
                        <b class="is-visible">code.</b>
                        <b>design.</b>
                        <b>marketing.</b>
                    </span>
            </h1>
                <h5>building apps for the web, Android phones and soon smart glasses</h5>
            </div>

            <div class="mouse">
                <div class="scroll"></div>
            </div>
        </section>

        <section>
          <div class="footer-top">
            <ul class="socials">
              <li class="facebook">
                <a href="https://www.facebook.com/preisler.io/" target="_blank" data-hover="Facebook">Facebook</a>
              </li>
              <li class="instagram">
                <a href="https://www.instagram.com/jonaspreisler/" target="_blank" data-hover="Instagram">Instagram</a>
              </li>
              <li class="gplus">
                <a href="https://www.youtube.com/c/jonaspreisler" target="_blank" data-hover="YouTube">YouTube</a>
              </li>
            </ul>
          </div>
        </section>

        <section class="box-intro2">
            <div class="table-cell">
                <h2><b>Check out some of my projects:</b></h2>
            </div>

            <div class="mouse">
                <div class="scroll"></div>
            </div>
        </section>
        <!-- end box-intro -->
    </div>
    <% @project.each do |project| %>
        <div class="card-deck">
          <div class="card portfolio_item">
            <center><%= image_tag project.image.url, class: "img-responsive card-img-top" %></center>
            <div class="portfolio_item_hover">
                <div class="portfolio-border clearfix">
                    <div class="item_info">
                        <span><%= link_to project.name, project %></span>
                        <em><%= link_to project.category.name, project %></em>
                    </div>
                </div>
            </div>
          </div>
        </div>
    <% end %>
</body>

</html>

app/views/portfolios/index.html.erb
<% @portfolio.each do |portfolio| %>
  <%= portfolio.name %><br>
<% end %>

app/views/portfolios/new.html.erb
<div class="container page-content">
  <div class="row">
    <div class-"span12">
      <div class="box-container">
        <div style="margin-left: auto; margin-right: auto; width: 20em" ><br />
          <h2 class="page-title">Add portfolio</h2>

          <%= simple_form_for(@portfolio) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :description %>
            <%= f.text_area :description %>

            <br />

            <%= f.label :category %>
            <%= f.select :category_id, Category.all.map{ |f| [f.name, f.id] } %>

            <%= f.label :link %>
            <%= f.text_field :link %>

            <br />
            
            <%= f.file_field :image %>

            <br />

            <%= f.submit "Opret", class: "btn span3 btn-realto-form btn-large" %>
          <% end %>
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/show.html.erb
<p><%= @portfolio.name %></p>

app/views/projects/_form.html.erb
<div class="container page-content">
  <div class="row">
    <div class-"span12">
      <div class="box-container">
        <div style="margin-left: auto; margin-right: auto; width: 20em" ><br />
          <h2 class="page-title">Add portfolio</h2>


          <%= simple_form_for(@project) do |f| %>
            <%= f.error_notification %>
            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :description %>
            <%= f.text_area :description %>

            <br>
            
            <%= f.label :link_string %>
            <%= f.text_field :link_string %>

            <br />

            <%= f.label :category %>
            <%= f.select :category_id, Category.all.map{ |f| [f.name, f.id] } %>


            
            <%= f.file_field :image %>
            <br />
            <div class="form-inputs">
            </div>

            <div class="form-actions">
              <%= f.button :submit %>
            </div>
          <% end %>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= render 'layouts/header2' %>

<!-- top-bar -->
<div class="top-bar">
    <p style="color:#CF2239"><%= @project.category.name %></p>
    <h1><%= link_to @project.link_string, "http://#{@project.link_string}", target: "_blank" %></h1>
    <br>
    <div class="card-deck">
      <div class="card portfolio_item">
        <%= image_tag @project.image.url, class: "img-responsive card-img-top" %>
      </div>
    </div>
</div>
<!-- end top-bar -->

<!-- main-container -->
<div class="container project-description">
        <p><%= h(@project.description).gsub(/\n/, '<br/>').html_safe %></p>
</div>
<br/>
<br/>
<br/>
<!-- end main-container -->

<!-- footer -->
<% render 'layouts/footer' %>
<!-- end footer -->

<!-- back to top -->
<a href="#0" class="cd-top"><i class="ion-android-arrow-up"></i></a>
<!-- end back to top -->




<!-- jQuery -->
<script src="js/jquery-2.1.1.js"></script>
<!--  plugins -->
<script src="js/bootstrap.min.js"></script>
<script src="js/menu.js"></script>
<script src="js/animated-headline.js"></script>
<script src="js/isotope.pkgd.min.js"></script>


<!--  custom script -->
<script src="js/custom.js"></script>